# Generated by Django 3.2.5 on 2021-07-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Statut',
            field=models.CharField(choices=[('en instance', 'en instance'), ('non valide', 'non valide'), ('valide', 'valide')], max_length=50, null=True),
        ),
    ]
