# Generated by Django 3.2.5 on 2021-08-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_alter_operation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='Statut',
            field=models.CharField(choices=[('en instance', 'en instance'), ('non valide', 'non valide'), ('valide', 'valide')], default=('en instance', 'en instance'), max_length=50, null=True),
        ),
    ]
